### ISSUE TITLE
Long descriptions duplicated

### ISSUE THREAD

**Issue by nastasi** [JCN-9000/MiniEPG#10]
To reproduce the bug:
- _from EPG:_ look a long description of some program
- _from EPG:_ look another long description of some program (that I suspect hasn't it) (on MTV8 channel in my case)
- at this point you can see the first long description instead of nothing

**Comment by JCN-9000** [comment]
Yes, I've seen this happen too. 
I think it is a BlobBox bug, since there are no wrong descriptions inside the EPG data. 
You can check the EPG file contents. 
It could be triggered by something inside the EPG file, but there is no way to debug the BB internals.

You can also try this:
_all inside EPG:_
- look a long description of some program. Let's call it **Desc A**
- look a long description on some _channel_ that misbehaves: you get **Desc A**
- look a long description of some other program, say **Desc B**
- go back to the long description that wrongly showed **Desc A**, now you get **Desc B**

For some reason on some channels the BB is not reading the description from the EPG, just showing the last description from memory.

**Comment by JCN-9000** [comment]
Should work now.
